/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.yorksolutions.tsg.feedbackapi.dtos;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Feedback extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 440244431329627560L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Feedback\",\"namespace\":\"net.yorksolutions.tsg.feedbackapi.dtos\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"logicalType\":\"uuid\"},{\"name\":\"memberId\",\"type\":\"string\"},{\"name\":\"providerName\",\"type\":\"string\"},{\"name\":\"rating\",\"type\":\"int\"},{\"name\":\"comment\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"submittedAt\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"schemaVersion\",\"type\":\"string\",\"doc\":\"Schema Version for Contract Evolution\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Feedback> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Feedback> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Feedback> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Feedback> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Feedback> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Feedback to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Feedback from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Feedback instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Feedback fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence memberId;
  private java.lang.CharSequence providerName;
  private int rating;
  private java.lang.CharSequence comment;
  private long submittedAt;
  /** Schema Version for Contract Evolution */
  private java.lang.CharSequence schemaVersion;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Feedback() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param memberId The new value for memberId
   * @param providerName The new value for providerName
   * @param rating The new value for rating
   * @param comment The new value for comment
   * @param submittedAt The new value for submittedAt
   * @param schemaVersion Schema Version for Contract Evolution
   */
  public Feedback(java.lang.CharSequence id, java.lang.CharSequence memberId, java.lang.CharSequence providerName, java.lang.Integer rating, java.lang.CharSequence comment, java.lang.Long submittedAt, java.lang.CharSequence schemaVersion) {
    this.id = id;
    this.memberId = memberId;
    this.providerName = providerName;
    this.rating = rating;
    this.comment = comment;
    this.submittedAt = submittedAt;
    this.schemaVersion = schemaVersion;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return memberId;
    case 2: return providerName;
    case 3: return rating;
    case 4: return comment;
    case 5: return submittedAt;
    case 6: return schemaVersion;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: memberId = (java.lang.CharSequence)value$; break;
    case 2: providerName = (java.lang.CharSequence)value$; break;
    case 3: rating = (java.lang.Integer)value$; break;
    case 4: comment = (java.lang.CharSequence)value$; break;
    case 5: submittedAt = (java.lang.Long)value$; break;
    case 6: schemaVersion = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'memberId' field.
   * @return The value of the 'memberId' field.
   */
  public java.lang.CharSequence getMemberId() {
    return memberId;
  }


  /**
   * Sets the value of the 'memberId' field.
   * @param value the value to set.
   */
  public void setMemberId(java.lang.CharSequence value) {
    this.memberId = value;
  }

  /**
   * Gets the value of the 'providerName' field.
   * @return The value of the 'providerName' field.
   */
  public java.lang.CharSequence getProviderName() {
    return providerName;
  }


  /**
   * Sets the value of the 'providerName' field.
   * @param value the value to set.
   */
  public void setProviderName(java.lang.CharSequence value) {
    this.providerName = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public int getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(int value) {
    this.rating = value;
  }

  /**
   * Gets the value of the 'comment' field.
   * @return The value of the 'comment' field.
   */
  public java.lang.CharSequence getComment() {
    return comment;
  }


  /**
   * Sets the value of the 'comment' field.
   * @param value the value to set.
   */
  public void setComment(java.lang.CharSequence value) {
    this.comment = value;
  }

  /**
   * Gets the value of the 'submittedAt' field.
   * @return The value of the 'submittedAt' field.
   */
  public long getSubmittedAt() {
    return submittedAt;
  }


  /**
   * Sets the value of the 'submittedAt' field.
   * @param value the value to set.
   */
  public void setSubmittedAt(long value) {
    this.submittedAt = value;
  }

  /**
   * Gets the value of the 'schemaVersion' field.
   * @return Schema Version for Contract Evolution
   */
  public java.lang.CharSequence getSchemaVersion() {
    return schemaVersion;
  }


  /**
   * Sets the value of the 'schemaVersion' field.
   * Schema Version for Contract Evolution
   * @param value the value to set.
   */
  public void setSchemaVersion(java.lang.CharSequence value) {
    this.schemaVersion = value;
  }

  /**
   * Creates a new Feedback RecordBuilder.
   * @return A new Feedback RecordBuilder
   */
  public static net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder newBuilder() {
    return new net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder();
  }

  /**
   * Creates a new Feedback RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Feedback RecordBuilder
   */
  public static net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder newBuilder(net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder other) {
    if (other == null) {
      return new net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder();
    } else {
      return new net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder(other);
    }
  }

  /**
   * Creates a new Feedback RecordBuilder by copying an existing Feedback instance.
   * @param other The existing instance to copy.
   * @return A new Feedback RecordBuilder
   */
  public static net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder newBuilder(net.yorksolutions.tsg.feedbackapi.dtos.Feedback other) {
    if (other == null) {
      return new net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder();
    } else {
      return new net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder(other);
    }
  }

  /**
   * RecordBuilder for Feedback instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Feedback>
    implements org.apache.avro.data.RecordBuilder<Feedback> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence memberId;
    private java.lang.CharSequence providerName;
    private int rating;
    private java.lang.CharSequence comment;
    private long submittedAt;
    /** Schema Version for Contract Evolution */
    private java.lang.CharSequence schemaVersion;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.memberId)) {
        this.memberId = data().deepCopy(fields()[1].schema(), other.memberId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.providerName)) {
        this.providerName = data().deepCopy(fields()[2].schema(), other.providerName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.rating)) {
        this.rating = data().deepCopy(fields()[3].schema(), other.rating);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.comment)) {
        this.comment = data().deepCopy(fields()[4].schema(), other.comment);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.submittedAt)) {
        this.submittedAt = data().deepCopy(fields()[5].schema(), other.submittedAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[6].schema(), other.schemaVersion);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Feedback instance
     * @param other The existing instance to copy.
     */
    private Builder(net.yorksolutions.tsg.feedbackapi.dtos.Feedback other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.memberId)) {
        this.memberId = data().deepCopy(fields()[1].schema(), other.memberId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.providerName)) {
        this.providerName = data().deepCopy(fields()[2].schema(), other.providerName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.rating)) {
        this.rating = data().deepCopy(fields()[3].schema(), other.rating);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.comment)) {
        this.comment = data().deepCopy(fields()[4].schema(), other.comment);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.submittedAt)) {
        this.submittedAt = data().deepCopy(fields()[5].schema(), other.submittedAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.schemaVersion)) {
        this.schemaVersion = data().deepCopy(fields()[6].schema(), other.schemaVersion);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'memberId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemberId() {
      return memberId;
    }


    /**
      * Sets the value of the 'memberId' field.
      * @param value The value of 'memberId'.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder setMemberId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.memberId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'memberId' field has been set.
      * @return True if the 'memberId' field has been set, false otherwise.
      */
    public boolean hasMemberId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'memberId' field.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder clearMemberId() {
      memberId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'providerName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProviderName() {
      return providerName;
    }


    /**
      * Sets the value of the 'providerName' field.
      * @param value The value of 'providerName'.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder setProviderName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.providerName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'providerName' field has been set.
      * @return True if the 'providerName' field has been set, false otherwise.
      */
    public boolean hasProviderName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'providerName' field.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder clearProviderName() {
      providerName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * @return The value.
      */
    public int getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder setRating(int value) {
      validate(fields()[3], value);
      this.rating = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'rating' field.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder clearRating() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'comment' field.
      * @return The value.
      */
    public java.lang.CharSequence getComment() {
      return comment;
    }


    /**
      * Sets the value of the 'comment' field.
      * @param value The value of 'comment'.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder setComment(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.comment = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'comment' field has been set.
      * @return True if the 'comment' field has been set, false otherwise.
      */
    public boolean hasComment() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'comment' field.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder clearComment() {
      comment = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'submittedAt' field.
      * @return The value.
      */
    public long getSubmittedAt() {
      return submittedAt;
    }


    /**
      * Sets the value of the 'submittedAt' field.
      * @param value The value of 'submittedAt'.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder setSubmittedAt(long value) {
      validate(fields()[5], value);
      this.submittedAt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'submittedAt' field has been set.
      * @return True if the 'submittedAt' field has been set, false otherwise.
      */
    public boolean hasSubmittedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'submittedAt' field.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder clearSubmittedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'schemaVersion' field.
      * Schema Version for Contract Evolution
      * @return The value.
      */
    public java.lang.CharSequence getSchemaVersion() {
      return schemaVersion;
    }


    /**
      * Sets the value of the 'schemaVersion' field.
      * Schema Version for Contract Evolution
      * @param value The value of 'schemaVersion'.
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder setSchemaVersion(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.schemaVersion = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'schemaVersion' field has been set.
      * Schema Version for Contract Evolution
      * @return True if the 'schemaVersion' field has been set, false otherwise.
      */
    public boolean hasSchemaVersion() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'schemaVersion' field.
      * Schema Version for Contract Evolution
      * @return This builder.
      */
    public net.yorksolutions.tsg.feedbackapi.dtos.Feedback.Builder clearSchemaVersion() {
      schemaVersion = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Feedback build() {
      try {
        Feedback record = new Feedback();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.memberId = fieldSetFlags()[1] ? this.memberId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.providerName = fieldSetFlags()[2] ? this.providerName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.rating = fieldSetFlags()[3] ? this.rating : (java.lang.Integer) defaultValue(fields()[3]);
        record.comment = fieldSetFlags()[4] ? this.comment : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.submittedAt = fieldSetFlags()[5] ? this.submittedAt : (java.lang.Long) defaultValue(fields()[5]);
        record.schemaVersion = fieldSetFlags()[6] ? this.schemaVersion : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Feedback>
    WRITER$ = (org.apache.avro.io.DatumWriter<Feedback>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Feedback>
    READER$ = (org.apache.avro.io.DatumReader<Feedback>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.memberId);

    out.writeString(this.providerName);

    out.writeInt(this.rating);

    out.writeString(this.comment);

    out.writeLong(this.submittedAt);

    out.writeString(this.schemaVersion);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.memberId = in.readString(this.memberId instanceof Utf8 ? (Utf8)this.memberId : null);

      this.providerName = in.readString(this.providerName instanceof Utf8 ? (Utf8)this.providerName : null);

      this.rating = in.readInt();

      this.comment = in.readString(this.comment instanceof Utf8 ? (Utf8)this.comment : null);

      this.submittedAt = in.readLong();

      this.schemaVersion = in.readString(this.schemaVersion instanceof Utf8 ? (Utf8)this.schemaVersion : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.memberId = in.readString(this.memberId instanceof Utf8 ? (Utf8)this.memberId : null);
          break;

        case 2:
          this.providerName = in.readString(this.providerName instanceof Utf8 ? (Utf8)this.providerName : null);
          break;

        case 3:
          this.rating = in.readInt();
          break;

        case 4:
          this.comment = in.readString(this.comment instanceof Utf8 ? (Utf8)this.comment : null);
          break;

        case 5:
          this.submittedAt = in.readLong();
          break;

        case 6:
          this.schemaVersion = in.readString(this.schemaVersion instanceof Utf8 ? (Utf8)this.schemaVersion : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










